Repository bcad1591/sidedish, pull requests merged in 2022-04, with the labels that each got.

#2 chore: CRA 기반 개발환경 설정 #1
  fe/.gitignore
  fe/.prettierrc
  fe/README.md
  fe/package-lock.json
  fe/package.json
  fe/public/index.html
  fe/src/App.css
  fe/src/App.jsx
  fe/src/index.css
  fe/src/index.js
Labels: chore

#5 Header Component 추가
  fe/package-lock.json
  fe/package.json
  fe/public/Mypage.svg
  fe/public/Search.svg
  fe/public/Shopping-cart.svg
  fe/src/App.css
  fe/src/App.jsx
  fe/src/Header.jsx
  fe/src/Menu.jsx
  fe/src/MenuList.jsx
  fe/src/index.css
Labels: feat

#7 msw 모듈 추가
  fe/package-lock.json
  fe/package.json
  fe/public/mockServiceWorker.js
  fe/src/index.js
  fe/src/mocks/browser.js
  fe/src/mocks/handlers.js
Labels: chore

#8 Refactor Header
  fe/src/App.jsx
  fe/src/Header.jsx
  fe/src/Header/Header.jsx
  fe/src/Header/Menu.jsx
  fe/src/Header/MenuList.jsx
  fe/src/Header/UserButtons.jsx
Labels: refactor

#12 Colors 상수 코드 구현
  fe/src/Constants/Colors.js
Labels: design

#13 Badge component 추가
  fe/src/Badge/CategoryBadge.jsx
  fe/src/Badge/DiscountBadge.jsx
Labels: design, refactor

#14 Typography 추가
  fe/public/logo.svg
  fe/src/Header/Header.jsx
  fe/src/Header/Menu.jsx
  fe/src/Header/MenuList.jsx
  fe/src/Header/UserButtons.jsx
  fe/src/index.css
Labels: design

#15 리뷰 반영 및 매직 리터럴 제거
  fe/src/Header/Header.jsx
  fe/src/Header/Menu.jsx
  fe/src/Header/MenuList.jsx
  fe/src/Header/UserButtons.jsx
Labels: refactor

#22 BestProducts 컴포넌트 추가 #21
  fe/.prettierrc
  fe/src/App.jsx
  fe/src/Badge/CategoryBadge.jsx
  fe/src/Badge/DiscountBadge.jsx
  fe/src/Header/Menu.jsx
  fe/src/Main/BestProducts.jsx
  fe/src/Main/Main.jsx
  fe/src/Main/ProductCard.jsx
  fe/src/index.css
  fe/src/mocks/handlers.js
Labels: design, feat

#24 CategoryList 컴포넌트 구현 #18
  fe/README.md
  fe/package-lock.json
  fe/package.json
  fe/src/App.jsx
  fe/src/Header/Header.jsx
  fe/src/Header/Menu.jsx
  fe/src/Header/MenuList.jsx
  fe/src/Main/BestProducts.jsx
  fe/src/Main/Category.jsx
  fe/src/Main/CategoryList.jsx
  fe/src/Main/Main.jsx
  fe/src/Main/ProductCard.jsx
  fe/src/index.css
  fe/src/mocks/handlers.js
Labels: design, feat

#25 [FE] 리팩토링 진행중
  fe/craco.config.js
  fe/jsconfig.json
  fe/jsconfig.paths.json
  fe/package-lock.json
  fe/package.json
  fe/src/App.jsx
  fe/src/Badge/CategoryBadge.jsx
  fe/src/Badge/DiscountBadge.jsx
  fe/src/Constants/Colors.js
  fe/src/Header/Header.jsx
  fe/src/Header/Menu.jsx
  fe/src/Header/MenuList.jsx
  fe/src/Header/UserButtons.jsx
  fe/src/Header/index.js
  fe/src/Main/BestProducts.jsx
  fe/src/Main/Category.jsx
  fe/src/Main/CategoryList.jsx
  fe/src/Main/Main.jsx
  fe/src/Main/ProductCard.jsx
  fe/src/Main/index.js
  fe/src/index.js
  fe/src/mocks/browser.js
Labels: refactor

#26 refactor: 폰트 클래스 네임 상수화
  fe/src/Constants/Fonts.js
Labels: refactor

#27 refactor: 리팩토링
  fe/jsconfig.json
  fe/jsconfig.paths.json
  fe/src/App.jsx
  fe/src/Header/Header.jsx
  fe/src/Header/Menu.jsx
  fe/src/Header/UserActionButtons.jsx
  fe/src/Main/Main.jsx
Labels: refactor

#28 베스트 프로덕트 리팩토링
  fe/src/Badge/DiscountBadge.jsx
  fe/src/Header/Menu.jsx
  fe/src/Header/MenuList.jsx
  fe/src/Main/BestProducts.jsx
  fe/src/Main/HoverInfo.jsx
  fe/src/Main/PriceTag.jsx
  fe/src/Main/ProductCard.jsx
  fe/src/Main/Tab.jsx
  fe/src/Main/TabList.jsx
Labels: refactor

#30 Refactor
  fe/jsconfig.json
  fe/jsconfig.paths.json
  fe/src/App.jsx
  fe/src/Components/App.jsx
  fe/src/Components/Badge/CategoryBadge.jsx
  fe/src/Components/Badge/DiscountBadge.jsx
  fe/src/Components/Header/Header.jsx
  fe/src/Components/Header/Menu.jsx
  fe/src/Components/Header/MenuList.jsx
  fe/src/Components/Header/UserActionButtons.jsx
  fe/src/Components/Header/index.js
  fe/src/Components/Main/BestProducts.jsx
  fe/src/Components/Main/Category.jsx
  fe/src/Components/Main/CategoryList.jsx
  fe/src/Components/Main/HoverInfo.jsx
  fe/src/Components/Main/Main.jsx
  fe/src/Components/Main/PriceTag.jsx
  fe/src/Components/Main/ProductCard.jsx
  fe/src/Components/Main/Tab.jsx
  fe/src/Components/Main/TabList.jsx
  fe/src/Components/Main/index.js
  fe/src/Utils/Utils.js
  fe/src/index.js
Labels: chore, refactor

#31 Refactor
  fe/src/Components/Header/Menu.jsx
  fe/src/Components/Main/BestProducts.jsx
  fe/src/Components/Main/Tab.jsx
  fe/src/Components/Main/TabList.jsx
  fe/src/mocks/handlers.js
Labels: refactor

#33 Refactor
  fe/package.json
  fe/src/Components/App.jsx
  fe/src/Components/BestProducts/BestProducts.jsx
  fe/src/Components/BestProducts/Tab.jsx
  fe/src/Components/BestProducts/TabList.jsx
  fe/src/Components/BestProducts/index.js
  fe/src/Components/CategoryProductsList/CategoryProducts.jsx
  fe/src/Components/CategoryProductsList/CategoryProductsList.jsx
  fe/src/Components/CategoryProductsList/index.js
  fe/src/Components/Header/Header.jsx
  fe/src/Components/Main/Main.jsx
  fe/src/Components/Main/index.js
  fe/src/Components/ProductCard/HoverInfo.jsx
  fe/src/Components/ProductCard/PriceTag.jsx
  fe/src/Components/ProductCard/ProductCard.jsx
  fe/src/Components/ProductCard/index.js
Labels: refactor

#40 CardProductsList 컴포넌트 리팩토링
  fe/src/Components/App.jsx
  fe/src/Components/Button/RetryButton.jsx
  fe/src/Components/Button/index.jsx
  fe/src/Components/CategoryProductsList/CategoryProducts.jsx
  fe/src/Components/CategoryProductsList/CategoryProductsList.jsx
  fe/src/Components/LoadingSpinner/index.jsx
  fe/src/Components/ProductCard/ProductCard.jsx
  fe/src/Hooks/useFetch.jsx
Labels: refactor

#41 아이콘 폰트 추가
  fe/public/Mypage.svg
  fe/public/Search.svg
  fe/public/Shopping-cart.svg
  fe/public/assets/fonts/sidedish.eot
  fe/public/assets/fonts/sidedish.svg
  fe/public/assets/fonts/sidedish.ttf
  fe/public/assets/fonts/sidedish.woff
  fe/public/logo.svg
  fe/src/Components/CategoryProductsList/CategoryProductsList.jsx
  fe/src/Components/Header/Header.jsx
  fe/src/Components/Header/UserActionButtons.jsx
  fe/src/Constants/IconFonts.js
  fe/src/Constants/index.js
  fe/src/icon-fonts.css
  fe/src/index.css
Labels: refactor

#43 feat #33 정적-모달창 구현
  fe/public/minus.svg
  fe/public/plus.svg
  fe/src/Components/App.jsx
  fe/src/Components/OrderModal/OrderPanel.jsx
  fe/src/Components/OrderModal/index.js
Labels: feat

#44 전체적인 리팩토링
  fe/src/Components/App.jsx
  fe/src/Components/Badge/CategoryBadge.jsx
  fe/src/Components/Badge/DiscountBadge.jsx
  fe/src/Components/Badge/index.jsx
  fe/src/Components/BestProducts/BestProducts.jsx
  fe/src/Components/BestProducts/Tab.jsx
  fe/src/Components/BestProducts/TabList.jsx
  fe/src/Components/BestProducts/index.jsx
  fe/src/Components/Button/RetryButton.jsx
  fe/src/Components/CategoryProductsList/CategoryProducts.jsx
  fe/src/Components/CategoryProductsList/CategoryProductsList.jsx
  fe/src/Components/CategoryProductsList/index.jsx
  fe/src/Components/Header/Header.jsx
  fe/src/Components/Header/Menu.jsx
  fe/src/Components/Header/MenuList.jsx
  fe/src/Components/Header/index.jsx
  fe/src/Components/LoadingSpinner/index.jsx
  fe/src/Components/OrderModal/OrderPanel.jsx
  fe/src/Components/OrderModal/index.jsx
  fe/src/Components/ProductCard/HoverInfo.jsx
  fe/src/Components/ProductCard/PriceTag.jsx
  fe/src/Components/ProductCard/ProductCard.jsx
  fe/src/Components/ProductCard/index.jsx
  fe/src/Constants/Colors.js
  fe/src/Constants/Fonts.js
  fe/src/Constants/index.js
  fe/src/Hooks/index.jsx
  fe/src/Hooks/useFetch.jsx
  fe/src/Utils/fetch.js
  fe/src/Utils/index.js
Labels: refactor

#45 Slider 추가
  fe/.gitignore
  fe/src/Components/CategoryProductsList/CategoryProducts.jsx
  fe/src/Env/index.js
Labels: feat

#47 [FE] 리팩토링
  fe/src/Components/App.jsx
  fe/src/Components/Badge/DiscountBadge.jsx
  fe/src/Components/BestProducts/BestProducts.jsx
  fe/src/Components/BestProducts/BestTemp.jsx
  fe/src/Components/BestProducts/Tab.jsx
  fe/src/Components/CategoryProductsList/CategoryProducts.jsx
  fe/src/Components/CategoryProductsList/CategoryProductsList.jsx
  fe/src/Components/Header/Header.jsx
  fe/src/Components/Header/Logo.jsx
  fe/src/Components/Header/Menu.jsx
  fe/src/Components/Header/MenuList.jsx
  fe/src/Components/LoadingSpinner/index.jsx
  fe/src/Components/ProductCard/ProductCard.jsx
  fe/src/Env/index.js
  fe/src/Hooks/useFetch.jsx
  fe/src/Utils/fetch.js
  fe/src/mocks/handlers.js
Labels: feat, refactor

#48 [FE][BE] Team-06 README 업데이트
  README.md
Labels: docs

#49 [FE][BE] Team-06 README 업데이트
  README.md
Labels: docs

#51 [FE] 제품 상세정보 모달창 구현
  fe/public/minus.svg
  fe/public/plus.svg
  fe/src/Components/App.jsx
  fe/src/Components/BestProducts/BestProducts.jsx
  fe/src/Components/BestProducts/Contents.jsx
  fe/src/Components/Button/AmountButton.jsx
  fe/src/Components/Button/OrderButton.jsx
  fe/src/Components/Button/index.jsx
  fe/src/Components/OrderModal/ModalContext.jsx
  fe/src/Components/OrderModal/OrderModal.jsx
  fe/src/Components/OrderModal/OrderPanel.jsx
  fe/src/Components/OrderModal/ProductAmount.jsx
  fe/src/Components/OrderModal/ProductInfo.jsx
  fe/src/Components/OrderModal/ProductThumbnail.jsx
  fe/src/Components/OrderModal/index.jsx
  fe/src/Components/ProductCard/ProductCard.jsx
  fe/src/Components/ProductCard/ProductThumbnail.jsx
Labels: feat, refactor

#53 [FE] 로딩 스피너 적용, 다시시도 버튼 적용
  fe/src/Components/App.jsx
  fe/src/Components/BestProducts/BestProducts.jsx
  fe/src/Components/BestProducts/Contents.jsx
  fe/src/Components/Button/RetryButton.jsx
  fe/src/Components/CategoryProductsList/CategoryProducts.jsx
  fe/src/Components/OrderModal/OrderModal.jsx
  fe/src/Components/OrderModal/index.jsx
Labels: design, refactor
